CREATE TABLE IF NOT EXISTS `tbl_user` (
    "id" number NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(30) DEFAULT NULL COMMENT '姓名',
    `age` int DEFAULT NULL COMMENT '年龄',
    `email` varchar(50) DEFAULT NULL COMMENT '邮箱',
    `creator` varchar(200) NOT NULL DEFAULT '',
    `updater` varchar(200) NOT NULL DEFAULT '',
    `create_time` datetime DEFAULT NULL,
    `update_time` datetime DEFAULT NULL,
    `deleted` tinyint(1) NOT NULL DEFAULT '0',
                        PRIMARY KEY (`id`)
) COMMENT = '用户';